### ISSUE TITLE
Error with array name in part 3

### ISSUE THREAD

**Issue by trishtracking** [oliverjam/learn-react#5]
Hey, I think I've spotted another error in 'date with a state' first bit --

In this section: 

-We use the React.useState method for this. It takes the initial state value as an argument, and returns an array. This array contains two things: the state value, and a function that lets you update the state value.

```function Counter(props) {
  const stateArray = React.useState(0);
  const count = countState[0];
  const setCount = countState[1];
  return <button>Count is {count}</button>;
}
``` 

I think `const stateArray = React.useState(0)` should be `const CountState` :)

**Comment by oliverjam** [comment]
You're right, thanks! Fixed in [this commit](https://github.com/oliverjam/learn-react/commit/206469c402f4445db07660ccf71046bd51e01384)
